# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    paths: 
    - 'this/tests/**'
    - 'this/testsIOS/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Update project
        working-directory: /Users/cobe/Documents/automation/test_Automation
        run: git pull origin main
      
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            android:
            - 'this/tests/**'
            ios:
            - 'this/testsIOS/**'
      
      - name: Run android tests
        working-directory: /Users/cobe/IdeaProjects/cucumber-testng-appium-raw
        if: steps.filter.outputs.android == 'true'
        run: mvn clean test -Dsurefire.suiteXmlFiles=/Users/cobe/IdeaProjects/cucumber-testng-appium-raw/src/test/resources/testngandroid.xml
        
      - name: Run ios tests
        working-directory: /Users/cobe/IdeaProjects/cucumber-testng-appium-raw
        if: steps.filter.outputs.ios == 'true'
        run: mvn clean test -Dsurefire.suiteXmlFiles=/Users/cobe/IdeaProjects/cucumber-testng-appium-raw/src/test/resources/testngios.xml
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: HTML report
          path: testing.txt
 
