# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    paths: 
    - 'this/tests/**'
    - 'this/testsIOS/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Update project
        working-directory: /Users/cobe/Documents/automation/test_Automation
        run: git pull origin main
      
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            android:
            - 'this/tests/**'
            ios:
            - 'this/testsIOS/**'
      
      - name: Run android tests
        working-directory: /Users/cobe/IdeaProjects/cucumber-testng-appium-raw
        if: steps.filter.outputs.android == 'true'
        run: mvn clean test -Dsurefire.suiteXmlFiles=/Users/cobe/IdeaProjects/cucumber-testng-appium-raw/src/test/resources/testngandroid.xml
        
      - name: Run ios tests
        working-directory: /Users/cobe/IdeaProjects/cucumber-testng-appium-raw
        if: steps.filter.outputs.ios == 'true'
        run: mvn clean test -Dsurefire.suiteXmlFiles=/Users/cobe/IdeaProjects/cucumber-testng-appium-raw/src/test/resources/testngios.xml
        
      - name: Upload a Build Artifact
        if: always()
        uses: actions/upload-artifact@v3.0.0
        with:
          name: HTML report
          path: /Users/cobe/IdeaProjects/cucumber-testng-appium-raw/target/Nexus_5X_API_30
          
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: kardum.vedran@gmail.com
          from: Luke Skywalker 
          secure: true
          body: Build job of ${{github.repository}} completed successfully!
          ignore_cert: true
          convert_markdown: true
          attachments: /Users/cobe/IdeaProjects/cucumber-testng-appium-raw/target/Nexus_5X_API_30
          priority: low
 
